### ISSUE TITLE
Return statement prevents callback from HTTP error triggering

### ISSUE THREAD

**Issue by synthecypher** [fvdm/nodejs-requestbin#11]
This return statement is preventing the callback being called, causing it to hang indefinitely.

I'm getting a `301` error by the way.

https://github.com/fvdm/nodejs-requestbin/blob/develop/requestbin.js#L46-L47

**Comment by fvdm** [comment]
Yikes, that’s a ugly mistake!
Working on it right away

**Comment by fvdm** [comment]
@synthecypher Fixed both issues and released v1.5.1 on npm.

Thanks for reporting.
